// Minimal ISO 4217 currency list. Order popular first, then rest alphabetically.
// Extend as needed.
export const ISO_4217: Array<{ label: string; value: string }> = [
  { label: 'USD — US Dollar', value: 'USD' },
  { label: 'EUR — Euro', value: 'EUR' },
  { label: 'INR — Indian Rupee', value: 'INR' },
  { label: 'GBP — British Pound', value: 'GBP' },
  { label: 'JPY — Japanese Yen', value: 'JPY' },
  { label: 'AUD — Australian Dollar', value: 'AUD' },
  { label: 'CAD — Canadian Dollar', value: 'CAD' },
  { label: 'CHF — Swiss Franc', value: 'CHF' },
  { label: 'CNY — Chinese Yuan', value: 'CNY' },
  { label: 'HKD — Hong Kong Dollar', value: 'HKD' },
  { label: 'NZD — New Zealand Dollar', value: 'NZD' },
  { label: 'SGD — Singapore Dollar', value: 'SGD' },
  { label: 'SEK — Swedish Krona', value: 'SEK' },
  { label: 'NOK — Norwegian Krone', value: 'NOK' },
  { label: 'DKK — Danish Krone', value: 'DKK' },
  { label: 'ZAR — South African Rand', value: 'ZAR' },
  { label: 'BRL — Brazilian Real', value: 'BRL' },
  { label: 'MXN — Mexican Peso', value: 'MXN' },
  { label: 'RUB — Russian Ruble', value: 'RUB' },
  { label: 'TRY — Turkish Lira', value: 'TRY' },
  { label: 'KRW — South Korean Won', value: 'KRW' },
  { label: 'IDR — Indonesian Rupiah', value: 'IDR' },
  { label: 'PLN — Polish Zloty', value: 'PLN' },
  { label: 'THB — Thai Baht', value: 'THB' },
  { label: 'AED — UAE Dirham', value: 'AED' },
  { label: 'SAR — Saudi Riyal', value: 'SAR' },
  { label: 'ILS — Israeli New Shekel', value: 'ILS' },
  { label: 'MYR — Malaysian Ringgit', value: 'MYR' },
  { label: 'PHP — Philippine Peso', value: 'PHP' },
  { label: 'NGN — Nigerian Naira', value: 'NGN' },
];
